[build]
  publish = "webapp/static"
  functions = "netlify/functions"
  command = "npm ci && cd webapp && npm ci"
  base = "."

[dev]
  publish = "webapp/static"
  port = 8888
  autoLaunch = true
  framework = "#static"
