[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# API redirects
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/api-simple/health"
  status = 200

[[redirects]]
  from = "/api/parse"
  to = "/.netlify/functions/api-simple/parse"
  status = 200

[[redirects]]
  from = "/api/test-connection"
  to = "/.netlify/functions/api-simple/test-connection"
  status = 200

# Test endpoint
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

# Catch all for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
